# argocd-job-restart-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: external-dns  # <--- The namespace showing the error in your logs
  name: argocd-job-restarter
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: external-dns
  name: argocd-job-restarter-binding
subjects:
  - kind: ServiceAccount
    name: argocd-server      # The SA running the Lua script
    namespace: argocd        # The namespace where ArgoCD is installed
roleRef:
  kind: Role
  name: argocd-job-restarter
  apiGroup: rbac.authorization.k8s.io