name: Enforce UV Usage

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  uv-governance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Install uv (needed to run the sync check)
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      # 2. Rule: No requirements.txt allowed in tracked files
      - name: 🚫 Check for forbidden requirements.txt
        run: |
          FORBIDDEN=$(git ls-files | grep -i "requirements.txt" || true)
          if [ -n "$FORBIDDEN" ]; then
            echo "❌ Policy Violation: Found tracked 'requirements.txt' files:"
            echo "$FORBIDDEN"
            echo "Please remove them and use 'pyproject.toml' + 'uv.lock'."
            exit 1
          fi