{{- $app := index (include "apps" $ | fromYaml) "external-dns" }}
{{- $values := $app.source.helm.values }}

{{- if $app.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $.Values.mox.cluster.name }}-{{ $app.name }}
  labels:
    cluster: {{ $.Values.mox.cluster.name }}
    env: {{ $.Values.mox.cluster.env }}
    type: {{ $.Values.mox.cluster.type }}
    app: {{ $app.name }}
    instance: {{ $app.name }}
    part-of: baseline
    subset: app
spec:
  project: {{ $.Values.mox.cluster.name }}-{{ $app.name }}
  destination:
    name: {{ $.Values.mox.cluster.name }}
    namespace: {{ $app.namespace.name }}
  
  # --- CHANGED: Using Multiple Sources ---
  sources:
    # Source 1: The Official Upstream Chart
    - repoURL: https://kubernetes-sigs.github.io/{{ $app.name }}
      chart: {{ $app.name }}
      targetRevision: {{ $values.chartVersion }}
      plugin:
        name: mox
        env:
          - name: helm
            value: |
              releaseName: {{ $app.name }}
              values:
                image:
                  repository: 030558737998.dkr.ecr.ap-east-1.amazonaws.com/{{ $app.name }}
                  tag: v{{ $values.imageVersion }}{{ $values.imageTagSuffix }}

                serviceAccount:
                  create: false
                  {{- if has $.Values.mox.cluster.type (list "integrations") }}
                  name: external-dns-public
                  {{- else }}
                  name: external-dns
                  {{- end }}

                resources:
                  requests:
                    memory: 100Mi
                    cpu: 10m
                  limits:
                    cpu: 50m
                    memory: 150Mi
                
                logLevel: error
                interval: 60s
                
                sources:
                  {{- if has $.Values.mox.cluster.type (list "aiden" "apps" "forgerock" "keycloak" "iaspec" "tm-vault" "vault") }}
                  - istio-gateway
                  {{- else if has $.Values.mox.cluster.type (list "crossenv" "cybsecops" "frontend") }}
                  - service
                  - ingress
                  {{- else }}
                  - service
                  {{- end }}

                # TODO: proper owner id
                {{- if (has $.Values.mox.cluster.type (list "frontend")) }}
                txtOwnerId: {{ $.Values.mox.cluster.type }}
                {{- else if has $.Values.mox.cluster.type (list "integrations") }}
                txtOwnerId: dev-{{ $.Values.mox.cluster.type }}-public
                {{- end }}

                {{- if and (has $.Values.mox.cluster.env (list "ptdev" "dev" "stg" "prod")) (has $.Values.mox.cluster.type (list "frontend")) }}
                policy: sync
                {{- else }}
                policy: upsert-only
                {{- end }}

                {{- if has $.Values.mox.cluster.type (list "frontend" "integrations") }}
                domainFilters:
                  {{- range $.Values.mox.cluster.dnsZones }}
                  {{ if contains $.Values.mox.cluster.region . }}
                  - '{{ . }}'
                  {{- end }}
                  {{- end }}
                {{- else }}
                domainFilters: {{ $.Values.mox.cluster.dnsZones | toJson }}
                {{- end }}

                provider: aws
                extraArgs:
                  - --aws-batch-change-size=1000
                  {{- if and (has $.Values.mox.cluster.type (list "frontend")) }}
                  {{- else if has $.Values.mox.cluster.type (list "integrations") }}
                  - --aws-zone-type=public
                  {{- else }}
                  - --aws-zone-type=private
                  {{- end }}
                  - --exclude-record-types=AAAA

    # Source 2: The Verifier Sidecar
    - repoURL: https://github.com/ProjectDrgn/argocd-apps
      path: apps/af-toolkit/verification/external-dns
      targetRevision: {{ $.Values.mox.argocd.branch }}
      plugin:
        name: mox
        env:
          - name: helm
            value: |
              hostedZoneId: "test"
              testDomainName: "test"
              targetNamespace: "verification-external-dns"
{{- end }}