# 1. ServiceAccount (The Identity)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns-verifier-sa
  namespace: af-toolkit # Must match where the Job runs
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded

---
# 2. ClusterRole / Role (The Permissions)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: external-dns-verifier-role
  # NOTE: This Namespace must be where the permissions are NEEDED (target)
  namespace: {{ .Values.targetNamespace }} 
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "get", "delete", "list"]

---
# 3. RoleBinding (Connecting Identity to Permissions)
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-dns-verifier-binding
  namespace: {{ .Values.targetNamespace }}
subjects:
  - kind: ServiceAccount
    name: external-dns-verifier-sa
    namespace: af-toolkit # Where the SA lives
roleRef:
  kind: Role
  name: external-dns-verifier-role
  apiGroup: rbac.authorization.k8s.io

---
# 4. The Job (The Workload)
apiVersion: batch/v1
kind: Job
metadata:
  name: external-dns-verifier
  namespace: af-toolkit
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: external-dns-verifier-sa
      restartPolicy: Never
      containers:
      - name: verifier
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
        - name: TARGET_NAMESPACE
          value: {{ .Values.targetNamespace | quote }}
        - name: HOSTED_ZONE_ID
          value: {{ .Values.hostedZoneId | quote }}
        - name: TEST_DOMAIN_NAME
          value: {{ .Values.testDomainName | quote }}