name: Ruff

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 1: Run Ruff Linter (Check for errors)
      # Defaults to 'ruff check' which looks for logic/style errors.
      - name: Ruff Check (Lint)
        uses: astral-sh/ruff-action@v3
        with:
            # We pin the version to avoid breaking changes in CI. 
            # It is best practice to keep this aligned with your local version.
            version: "0.9.1"
            # args: "check --output-format=github" # (The action does this automatically)

      # Step 2: Run Ruff Formatter (Check for formatting compliance)
      # We use 'format --check' so it fails if files are not formatted, 
      # rather than auto-formatting them silently.
      - name: Ruff Format (Style)
        uses: astral-sh/ruff-action@v3
        with:
          version: "0.9.1"
          args: "format --check"