apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  resource.customizations.actions.batch_Job: |
    discovery.lua: |
      actions = {}
      local status = obj.status or {}
      if status.failed ~= nil or status.succeeded ~= nil then
        table.insert(actions, {name = "retry", disabled = false})
      end
      return actions
    definitions:
    - name: retry
      action.lua: |
        local os = require("os")
        local job = {}
        job.apiVersion = obj.apiVersion
        job.kind = obj.kind
        job.metadata = {}
        job.metadata.name = obj.metadata.name .. "-retry-" .. tostring(os.time())
        job.metadata.namespace = obj.metadata.namespace
        if obj.metadata.labels then
          job.metadata.labels = {}
          for k, v in pairs(obj.metadata.labels) do
            job.metadata.labels[k] = v
          end
        end
        if obj.metadata.annotations then
          job.metadata.annotations = {}
          for k, v in pairs(obj.metadata.annotations) do
            job.metadata.annotations[k] = v
          end
        end
        job.metadata.labels["app.kubernetes.io/instance"] = obj.metadata.labels["app.kubernetes.io/instance"]
        job.metadata.annotations["argocd.argoproj.io/compare-options"] = "IgnoreExtraneous"
        job.spec = {}
        job.spec.template = obj.spec.template
        job.spec.backoffLimit = obj.spec.backoffLimit
        job.spec.activeDeadlineSeconds = obj.spec.activeDeadlineSeconds
        job.spec.ttlSecondsAfterFinished = obj.spec.ttlSecondsAfterFinished
        if job.spec.template.metadata == nil then
          job.spec.template.metadata = {}
        end
        if job.spec.template.metadata.labels then
          job.spec.template.metadata.labels["controller-uid"] = nil
          job.spec.template.metadata.labels["job-name"] = nil
        end
        return {
          {
            operation = "create",
            resource = job
          }
        }