apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  resource.customizations.ignoreDifferences.batch_Job: |
    jsonPointers:
    - /spec/template/metadata/labels/controller-uid
  
  # Define the custom action
  resource.customizations.actions.batch_Job: |
    discovery.lua: |
      actions = {}
      -- Only show the button if the user added the specific label
      if obj.metadata.labels and obj.metadata.labels["argocd.custom-action/retryable"] == "true" then
        actions["retry"] = {
          name = "Retry Job",
          title = "Retry",
          disabled = false
        }
      end
      return actions

    definitions:
    - name: retry
      action.lua: |
        local os = require("os")
        
        -- Create a copy of the existing object
        local newObj = {}
        newObj.apiVersion = obj.apiVersion
        newObj.kind = obj.kind
        newObj.metadata = {}
        newObj.spec = obj.spec

        -- Clean up metadata to ensure it's treated as a new object
        -- We append a timestamp to the name to avoid collision
        newObj.metadata.name = obj.metadata.name .. "-retry-" .. os.time()
        newObj.metadata.namespace = obj.metadata.namespace
        newObj.metadata.labels = obj.metadata.labels
        
        -- IMPORTANT: Clean up selector and controller-uid so K8s generates new ones
        newObj.spec.selector = nil
        newObj.spec.template.metadata.labels["controller-uid"] = nil
        
        -- Return the instruction to create this new resource
        return {
          k8s = {
            version = "batch/v1",
            kind = "Job",
            operation = "create",
            resource = newObj
          }
        }