apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ephemeral-env-manager
rules:
  # ---------------------------------------------------------
  # RULE 1: STRICT DELETE (The Security Guard)
  # Restricts "destroy" power to ONLY the specific namespace.
  # ---------------------------------------------------------
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["delete", "get"]
    resourceNames: ["verification-external-dns"] # <--- CRITICAL SECURITY LOCK

  # ---------------------------------------------------------
  # RULE 2: GLOBAL CREATE (The Necessary Evil)
  # K8s RBAC cannot restrict "create" by name. 
  # This allows creating ANY namespace, but Rule 1 limits cleanup.
  # ---------------------------------------------------------
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["create"] 

  # ---------------------------------------------------------
  # RULE 3: BOOTSTRAP PERMISSION (The Self-Binder)
  # Allows the job to grant ITSELF admin rights inside the new namespace.
  # This allows "kubectl create rolebinding" to run successfully.
  # ---------------------------------------------------------
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["rolebindings"]
    verbs: ["create"]


apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-ephemeral-access
subjects:
  - kind: ServiceAccount
    name: external-dns      # Your existing SA
    namespace: external-dns # Where the SA lives
roleRef:
  kind: ClusterRole
  name: ephemeral-env-manager
  apiGroup: rbac.authorization.k8s.io