apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  resource.customizations.actions.batch_Job: |
    # 1. Discovery (Unchanged - keeps your label check)
    discovery.lua: |
      actions = {}
      if obj.metadata.labels ~= nil and obj.metadata.labels["argocd.custom-action/retryable"] == "true" then
        actions["restart"] = {}
      end
      return actions

    # 2. Definitions (Unchanged)
    definitions:
      - name: restart
        title: Restart Job
        message: Creating a new Job from this spec...
        icon: replay

    # 3. Action Logic (Fixed & Robust)
    action.lua: |
      local os = require("os")
      
      -- Simplified Deep Copy (Safe for K8s objects)
      local function deepCopy(orig)
          local orig_type = type(orig)
          local copy
          if orig_type == 'table' then
              copy = {}
              for orig_key, orig_value in next, orig, nil do
                  copy[deepCopy(orig_key)] = deepCopy(orig_value)
              end
          else -- number, string, boolean, etc
              copy = orig
          end
          return copy
      end

      -- Initialize new Job
      local newJob = {}
      newJob.apiVersion = "batch/v1"
      newJob.kind = "Job"
      newJob.metadata = {}
      
      -- Generate Name (Safe Length)
      local baseName = obj.metadata.name
      if string.len(baseName) > 40 then
        baseName = string.sub(baseName, 1, 40)
      end
      -- Use os.time() as a fallback for uniqueness
      newJob.metadata.name = baseName .. "-rst-" .. os.time()
      newJob.metadata.namespace = obj.metadata.namespace

      -- Copy Labels
      if obj.metadata.labels then
        newJob.metadata.labels = deepCopy(obj.metadata.labels)
      else
        newJob.metadata.labels = {}
      end
      newJob.metadata.labels["argocd-action"] = "restarted-job"

      -- Handle Annotations (Strip Hooks/Tracking)
      if obj.metadata.annotations then
        newJob.metadata.annotations = deepCopy(obj.metadata.annotations)
        newJob.metadata.annotations["argocd.argoproj.io/hook"] = nil
        newJob.metadata.annotations["kubectl.kubernetes.io/last-applied-configuration"] = nil
        newJob.metadata.annotations["argocd.argoproj.io/tracking-id"] = nil
      end

      -- Copy Spec
      if obj.spec then
        newJob.spec = deepCopy(obj.spec)
        newJob.spec.selector = nil -- Reset selector
        
        -- Safe label assignment for the pod template
        if newJob.spec.template and newJob.spec.template.metadata then
             newJob.spec.template.metadata.labels = newJob.metadata.labels
        end
      end

      -- Return Result
      local result = {}
      result[1] = {
        operation = "create",
        resource = newJob
      }
      return result