apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  resource.customizations.actions.batch_Job: |
    # 1. Discovery: Check for the specific label
    discovery.lua: |
      actions = {}
      -- Safely check if labels exist, then check for the specific key/value
      if obj.metadata.labels ~= nil and obj.metadata.labels["argocd.custom-action/retryable"] == "true" then
        actions["restart"] = {}
      end
      return actions

    # 2. Definitions: UI Configuration
    definitions:
      - name: restart
        title: Restart Job
        message: Creating a new Job from this spec...
        icon: replay

    # 3. Action Logic: (Same as before)
    action.lua: |
      local os = require("os")

      -- Deep copy helper
      function deepCopy(object)
          local lookup_table = {}
          local function _copy(obj)
              if type(obj) ~= "table" then
                  return obj
              elseif lookup_table[obj] then
                  return lookup_table[obj]
              end
              local new_table = {}
              lookup_table[obj] = new_table
              for key, value in pairs(obj) do
                  new_table[_copy(key)] = _copy(value)
              end
              return setmetatable(new_table, getmetatable(obj))
          end
          return _copy(object)
      end

      local newJob = {}
      newJob.apiVersion = "batch/v1"
      newJob.kind = "Job"
      newJob.metadata = {}
      
      -- Generate unique name
      local baseName = obj.metadata.name
      if string.len(baseName) > 45 then
        baseName = string.sub(baseName, 1, 45)
      end
      newJob.metadata.name = baseName .. "-rst-" .. os.date("%Y%m%d%H%M%S")
      newJob.metadata.namespace = obj.metadata.namespace

      -- Copy Labels
      if obj.metadata.labels ~= nil then
        newJob.metadata.labels = deepCopy(obj.metadata.labels)
      else
        newJob.metadata.labels = {}
      end
      -- Ensure the new job also has the retryable label (optional, keeps it restartable)
      newJob.metadata.labels["argocd-action"] = "restarted-job"

      -- Handle Annotations (Strip ArgoCD hooks/tracking)
      if obj.metadata.annotations ~= nil then
        newJob.metadata.annotations = deepCopy(obj.metadata.annotations)
        newJob.metadata.annotations["argocd.argoproj.io/hook"] = nil
        newJob.metadata.annotations["kubectl.kubernetes.io/last-applied-configuration"] = nil
        newJob.metadata.annotations["argocd.argoproj.io/tracking-id"] = nil
      end

      -- Copy Spec
      newJob.spec = deepCopy(obj.spec)
      newJob.spec.selector = nil -- Let k8s generate a new selector
      newJob.spec.template.metadata.labels = newJob.metadata.labels

      local result = {}
      result[1] = {
        operation = "create",
        resource = newJob
      }
      return result