apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  resource.customizations.actions.batch_Job: |
    definitions:
    - name: retry
      action.lua: |
        local os = require("os")
        local newJob = {}
        newJob.apiVersion = "batch/v1"
        newJob.kind = "Job"
        newJob.metadata = {}
        newJob.metadata.name = obj.metadata.name .. "-retry-" .. os.time()
        newJob.metadata.namespace = obj.metadata.namespace
        newJob.metadata.labels = {}
        if obj.metadata.labels then
          for k,v in pairs(obj.metadata.labels) do
            newJob.metadata.labels[k] = v
          end
        end
        newJob.metadata.labels["controller-uid"] = nil
        newJob.metadata.labels["job-name"] = nil
        newJob.spec = obj.spec
        newJob.spec.selector = nil
        newJob.spec.template.metadata.labels["controller-uid"] = nil
        newJob.spec.template.metadata.labels["job-name"] = nil
        return {
          k8s = {
            version = "batch/v1",
            kind = "Job",
            operation = "create",
            resource = newJob
          }
        }
    discovery.lua: |
      actions = {}
      if obj.metadata.labels["argocd.custom-action/retryable"] == "true" then
        actions["retry"] = {
          name = "Retry Verification",
          title = "Retry Verification",
          disabled = false
        }
      end
      return actions