apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-verify-configmap
  namespace: af-toolkit
data:
  test-apps.yaml: |
    apiVersion: v1
    kind: Namespace
    metadata:
      name: {TEST_NAMESPACE}
      labels:
        istio.io/rev: {ISTIO_REVISION}
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: test-target-app
      namespace: {TEST_NAMESPACE}
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: test-target-app
      template:
        metadata:
          labels:
            app: test-target-app
        spec:
          containers:
          - name: template-service
            image: 030558737990.dkr.ecr.ap-east-1.amazonaws.com/platform-runtime-java17:v3
            ports:
            - containerPort: 8080
    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: test-target-app
      namespace: {TEST_NAMESPACE}
    spec:
      ports:
      - name: http
        port: 8000
        targetPort: 8080
      selector:
        app: test-target-app
    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: curl-client
      namespace: {TEST_NAMESPACE}
      labels:
        app: curl-client # <-- ADD THIS LABEL
    spec:
      containers:
      - name: curl
        image: curlimages/curl:latest # <-- Make sure this is whitelisted
        command: ["sleep", "3600"]
  
  # ... (no-sidecar-curl.yaml and mtls-strict.yaml are unchanged) ...
  no-sidecar-curl.yaml: |
    # ...
  mtls-strict.yaml: |
    # ...
  
  ingress.yaml: |
    # ... (ingress.yaml is unchanged) ...

  # --- ADD THIS NEW FILE ---
  retry-vs.yaml: |
    apiVersion: networking.istio.io/v1alpha3
    kind: VirtualService
    metadata:
      name: retry-test-vs
      namespace: {TEST_NAMESPACE}
    spec:
      hosts:
      - "test-target-app.{TEST_NAMESPACE}.svc.cluster.local"
      http:
      - match:
        - uri:
            prefix: /retry-test # We will curl this path
        fault: # Server-side: inject a 503 error
          abort:
            httpStatus: 503
            percentage:
              value: 100
        headers: # Server-side: add the retry-after header
          response:
            set:
              "retry-after": "2" # Tell client to wait 2 seconds
        route:
        - destination:
            host: "test-target-app.{TEST_NAMESPACE}.svc.cluster.local"
            port:
              number: 8000
        retries: # Client-side: enable retries
          attempts: 3
          perTryTimeout: 3s
          retryOn: "503,gateway-error,connect-failure"
      - route: # Default route for other paths
        - destination:
            host: "test-target-app.{TEST_NAMESPACE}.svc.cluster.local"
            port:
              number: 8000

  # --- ADD THIS NEW FILE ---
  retry-envoyfilter.yaml: |
    apiVersion: networking.istio.io/v1alpha3
    kind: EnvoyFilter
    metadata:
      name: retry-after-filter
      namespace: {TEST_NAMESPACE} # Must be in the same namespace as the client
    spec:
      workloadSelector:
        labels:
          app: curl-client # Targets our test pod
      configPatches:
      - applyTo: HTTP_ROUTE
        match:
          context: SIDECAR_OUTBOUND
          routeConfiguration:
            vhost:
              # Matches the route to our test service
              name: "test-target-app.{TEST_NAMESPACE}.svc.cluster.local:8000"
        patch:
          operation: MERGE
          value:
            retry_policy:
              # This tells the retry policy to read the header
              rate_limited_retry_back_off:
                reset_headers:
                - name: "retry-after"
                  format: SECONDS
                max_interval: "5s" # Max time to wait