cat <<EOF | kubectl apply -n argocd -f -
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  resource.customizations.actions.batch_Job: |
    discovery.lua: |
      actions = {}
      if obj.metadata.labels and obj.metadata.labels["argocd.custom-action/retryable"] == "true" then
        actions["restart"] = {}
      end
      return actions
    definitions:
      - name: restart
        title: Restart Job
        message: Restarting Job...
        icon: replay
        action.lua: |
          local os = require("os")
          local result = {}

          -- 1. Hardcoded App Name (Derived from your screenshot)
          -- This is required because we cannot parse strings in your environment.
          local myAppName = "hk-ptdev-crossenv.external-dns"

          local function deepCopy(obj)
            local lookup = {}
            local function _copy(o)
              if type(o) ~= "table" then return o end
              if lookup[o] then return lookup[o] end
              local new = {}
              lookup[o] = new
              for k, v in pairs(o) do new[_copy(k)] = _copy(v) end
              return new
            end
            return _copy(obj)
          end

          local function cleanPodSpec(podSpec)
            if not podSpec then return end
            if podSpec.securityContext and next(podSpec.securityContext) == nil then podSpec.securityContext = nil end
            local function cleanContainers(containers)
              if not containers then return end
              for _, c in pairs(containers) do
                if c.resources and next(c.resources) == nil then c.resources = nil end
                if c.securityContext and next(c.securityContext) == nil then c.securityContext = nil end
              end
            end
            cleanContainers(podSpec.containers)
            cleanContainers(podSpec.initContainers)
          end

          if obj then
            local baseName = obj.metadata.name or "job"
            
            -- Note: We cannot truncate safely without string lib, 
            -- so we use a very short suffix to minimize risk of "Name too long" errors.
            local newName = baseName .. "-r" .. os.time()

            local newJob = {
              apiVersion = "batch/v1",
              kind = "Job",
              metadata = {},
              spec = deepCopy(obj.spec or {})
            }

            newJob.metadata.name = newName
            newJob.metadata.namespace = obj.metadata.namespace
            
            local labels = deepCopy(obj.metadata.labels or {})
            
            -- 2. Strip System Labels (Fixes Ghost Job)
            labels["controller-uid"] = nil
            labels["batch.kubernetes.io/controller-uid"] = nil
            labels["job-name"] = nil
            labels["batch.kubernetes.io/job-name"] = nil
            
            -- 3. FORCE APP LINKING (Fixes Visibility)
            labels["app.kubernetes.io/instance"] = myAppName
            labels["argocd-action"] = "restarted-job"
            
            newJob.metadata.labels = labels

            -- 4. Clean Annotations (Safety)
            if obj.metadata.annotations then
              newJob.metadata.annotations = deepCopy(obj.metadata.annotations)
              -- Do NOT include tracking-id (prevents sync conflicts)
              newJob.metadata.annotations["argocd.argoproj.io/tracking-id"] = nil
              newJob.metadata.annotations["argocd.argoproj.io/hook"] = nil
              newJob.metadata.annotations["kubectl.kubernetes.io/last-applied-configuration"] = nil
              -- Prevent Auto-Deletion
              newJob.metadata.annotations["argocd.argoproj.io/sync-options"] = "Prune=false"
            else
              newJob.metadata.annotations = {}
              newJob.metadata.annotations["argocd.argoproj.io/sync-options"] = "Prune=false"
            end

            -- Reset Spec
            newJob.spec.selector = nil
            newJob.spec.template.metadata.creationTimestamp = nil
            if newJob.spec.template then
               if not newJob.spec.template.metadata then newJob.spec.template.metadata = {} end
               newJob.spec.template.metadata.labels = deepCopy(newJob.metadata.labels)
               if newJob.spec.template.spec then cleanPodSpec(newJob.spec.template.spec) end
            end

            result[1] = { operation = "create", resource = newJob }
          end
          return result
EOF