apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: namespace-admin
  namespace: target-namespace-name
subjects:
- kind: ServiceAccount
  name: my-service-account
  namespace: management-ns
roleRef:
  kind: ClusterRole
  name: admin # This is a built-in K8s role
  apiGroup: rbac.authorization.k8s.io