apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  resource.customizations.ignoreDifferences.batch_Job: |
    jsonPointers:
    - /spec/template/metadata/labels/controller-uid

  # Define the Custom Action for Batch/Job
  resource.customizations.actions.batch_Job: |
    discovery.lua: |
      -- Only show this button if the job looks like a verification job
      actions = {}
      if obj.metadata.name:match("^verification%-") then
        actions["retry-verification"] = {
          ["title"] = "Retry Verification",
          ["icon"] = "fa-redo",
          ["description"] = "Creates a new copy of this job to re-run verification"
        }
      end
      return actions

    definitions:
      - name: retry-verification
        action.lua: |
          local os = require("os")
          local newJob = {}
          
          -- Copy the base structure
          newJob.apiVersion = obj.apiVersion
          newJob.kind = obj.kind
          newJob.metadata = {}
          
          -- Generate a unique name for the retry
          newJob.metadata.name = obj.metadata.name .. "-retry-" .. os.time()
          newJob.metadata.namespace = obj.metadata.namespace
          newJob.metadata.labels = obj.metadata.labels
          newJob.metadata.annotations = obj.metadata.annotations
          
          -- Copy the Spec
          newJob.spec = obj.spec
          
          -- CRITICAL: Clean up fields that bind the job to the old instance
          newJob.spec.selector = nil  -- Let K8s generate a new selector
          if newJob.spec.template.metadata.labels then
            newJob.spec.template.metadata.labels["controller-uid"] = nil
          end
          
          return newJob