cat <<EOF | kubectl apply -n argocd -f -
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  resource.customizations.actions.batch_Job: |
    discovery.lua: |
      actions = {}
      if obj.metadata.labels and obj.metadata.labels["argocd.custom-action/retryable"] == "true" then
        actions["restart"] = {}
      end
      return actions
    definitions:
      - name: restart
        title: Restart Job
        message: Restarting Job...
        icon: replay
        action.lua: |
          local os=require("os"); local result={}; 
          local function deepCopy(o) if type(o)~="table" then return o end local c={} for k,v in pairs(o) do c[deepCopy(k)]=deepCopy(v) end return c end
          
          if obj then
            local baseName = obj.metadata.name or "job"
            -- FIX: Use # operator instead of string.len to avoid nil error
            if #baseName > 40 then 
              -- FIX: Use method syntax (:sub) instead of string.sub
              baseName = baseName:sub(1, 40) 
            end
            
            local newJob={apiVersion="batch/v1", kind="Job", metadata={}, spec=deepCopy(obj.spec or {})}
            newJob.metadata.name=baseName.."-rst-"..os.time()
            newJob.metadata.namespace=obj.metadata.namespace
            newJob.metadata.labels=deepCopy(obj.metadata.labels or {})
            newJob.metadata.labels["argocd-action"]="restarted-job"
            
            if obj.metadata.annotations then 
              newJob.metadata.annotations=deepCopy(obj.metadata.annotations)
              newJob.metadata.annotations["argocd.argoproj.io/hook"]=nil
              newJob.metadata.annotations["argocd.argoproj.io/tracking-id"]=nil
              newJob.metadata.annotations["kubectl.kubernetes.io/last-applied-configuration"]=nil 
            end
            
            newJob.spec.selector=nil
            if newJob.spec.template and newJob.spec.template.metadata then 
              newJob.spec.template.metadata.labels=newJob.metadata.labels 
            end
            
            result[1]={operation="create", resource=newJob}
          end
          return result
EOF