apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-verify-configmap
  namespace: af-toolkit
data:
  test-apps.yaml: |
    apiVersion: v1
    kind: Namespace
    metadata:
      name: {TEST_NAMESPACE}
      labels:
        istio.io/rev: {ISTIO_REVISION}
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: test-target-app
      namespace: {TEST_NAMESPACE}
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: test-target-app
      template:
        metadata:
          labels:
            app: test-target-app
        spec:
          containers:
          - name: template-service
            image: 030558737990.dkr.ecr.ap-east-1.amazonaws.com/platform-runtime-java17:v3
            ports:
            - containerPort: 8080
    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: test-target-app
      namespace: {TEST_NAMESPACE}
    spec:
      ports:
      - name: http
        port: 8000
        targetPort: 8080
      selector:
        app: test-target-app
    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: curl-client
      namespace: {TEST_NAMESPACE}
      labels:
        app: curl-client # <-- ADD THIS LABEL
    spec:
      containers:
      - name: curl
        image: curlimages/curl:latest # <-- Make sure this is whitelisted
        command: ["sleep", "3600"]
  
  # ... (no-sidecar-curl.yaml and mtls-strict.yaml are unchanged) ...
  no-sidecar-curl.yaml: |
    # ...
  mtls-strict.yaml: |
    # ...
  
  ingress.yaml: |
    # ... (ingress.yaml is unchanged) ...

  # --- ADD THIS NEW FILE ---
  retry-vs.yaml: |
    apiVersion: networking.istio.io/v1alpha3
    kind: VirtualService
    metadata:
      name: retry-after-test-vs
      namespace: {{TEST_NAMESPACE}}
    spec:
      hosts:
      - "retry-test.local" # A fake host just for this test
      gateways:
      - mesh # Apply to all sidecars in the mesh
      http:
      - name: "retry-route" # We will patch this route name
        match:
        - uri:
            prefix: "/test-retry"
        fault:
          abort:
            httpStatus: 503 # 1. Force a 503 to trigger the retry
            percentage:
              value: 100.0
        retries:
          attempts: 3 # 2. Allow 3 total attempts
          perTryTimeout: 1s
          retryOn: "gateway-error,connect-failure,503"
        headers:
          response:
            set:
              "retry-after": "2" # 3. Tell the client to wait 2 seconds
        route:
        - destination:
            # Route to a fake host. It doesn't matter,
            # the 'fault' will happen before the request is sent.
            host: "blackhole.local"
            port:
              number: 80

  # --- ADD THIS NEW FILE ---
  retry-envoyfilter.yaml: |
    apiVersion: networking.istio.io/v1alpha3
    kind: EnvoyFilter
    metadata:
      name: retry-after-test-ef
      namespace: {{TEST_NAMESPACE}}
    spec:
      workloadSelector:
        labels:
          app: af-toolkit # !!! IMPORTANT: Assumes this label is on your test pod
      configPatches:
      - applyTo: HTTP_ROUTE
        match:
          context: SIDECAR_OUTBOUND
          routeConfiguration:
            vhost:
              name: "retry-test.local:80" # Must match the VS host/port
              route:
                name: "retry-route" # Must match the VS route name
        patch:
          operation: MERGE
          value:
            retry_policy:
              # This is the "magic" that enables respecting the header
              rate_limited_retry_back_off:
                reset_headers:
                - name: "retry-after"
                  format: SECONDS
              # Set a max, so a bad server (e.g., "retry-after: 300")
              # doesn't stall the test for 5 minutes.
              max_interval: "5s"
