cat <<EOF | kubectl apply -n argocd -f -
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  resource.customizations.actions.batch_Job: |
    discovery.lua: |
      actions = {}
      if obj.metadata.labels and obj.metadata.labels["argocd.custom-action/retryable"] == "true" then
        actions["restart"] = {}
      end
      return actions
    definitions:
      - name: restart
        title: Restart Job
        message: Restarting Job...
        icon: replay
        action.lua: |
          local os = require("os")
          local result = {}

          -- 1. Helper: Deep Copy
          local function deepCopy(obj)
            local lookup = {}
            local function _copy(o)
              if type(o) ~= "table" then return o end
              if lookup[o] then return lookup[o] end
              local new = {}
              lookup[o] = new
              for k, v in pairs(o) do new[_copy(k)] = _copy(v) end
              return new
            end
            return _copy(obj)
          end

          -- 2. Helper: Clean Empty Tables
          -- Removes empty tables {} so they don't become [] and crash K8s
          local function cleanPodSpec(podSpec)
            if not podSpec then return end

            -- Clean Pod-Level Objects
            if podSpec.securityContext and next(podSpec.securityContext) == nil then podSpec.securityContext = nil end
            if podSpec.nodeSelector and next(podSpec.nodeSelector) == nil then podSpec.nodeSelector = nil end
            if podSpec.affinity and next(podSpec.affinity) == nil then podSpec.affinity = nil end
            if podSpec.tolerations and next(podSpec.tolerations) == nil then podSpec.tolerations = nil end

            -- Clean Container-Level Objects
            local function cleanContainers(containers)
              if not containers then return end
              for _, c in pairs(containers) do
                if c.resources and next(c.resources) == nil then c.resources = nil end
                if c.securityContext and next(c.securityContext) == nil then c.securityContext = nil end
                if c.lifecycle and next(c.lifecycle) == nil then c.lifecycle = nil end
              end
            end

            cleanContainers(podSpec.containers)
            cleanContainers(podSpec.initContainers)
          end

          -- 3. Main Logic
          if obj then
            local baseName = obj.metadata.name or "job"
            if #baseName > 40 then baseName = baseName:sub(1, 40) end

            local newJob = {
              apiVersion = "batch/v1",
              kind = "Job",
              metadata = {},
              spec = deepCopy(obj.spec or {})
            }

            -- Set Metadata
            newJob.metadata.name = baseName .. "-rst-" .. os.time()
            newJob.metadata.namespace = obj.metadata.namespace
            newJob.metadata.labels = deepCopy(obj.metadata.labels or {})
            newJob.metadata.labels["argocd-action"] = "restarted-job"

            -- Clean Annotations
            if obj.metadata.annotations then
              newJob.metadata.annotations = deepCopy(obj.metadata.annotations)
              newJob.metadata.annotations["argocd.argoproj.io/hook"] = nil
              newJob.metadata.annotations["argocd.argoproj.io/tracking-id"] = nil
              newJob.metadata.annotations["kubectl.kubernetes.io/last-applied-configuration"] = nil
            end

            -- Reset Spec
            newJob.spec.selector = nil
            if newJob.spec.template then
               if not newJob.spec.template.metadata then newJob.spec.template.metadata = {} end
               newJob.spec.template.metadata.labels = deepCopy(newJob.metadata.labels)
               
               -- RUN THE CLEANER
               if newJob.spec.template.spec then
                 cleanPodSpec(newJob.spec.template.spec)
               end
            end

            result[1] = { operation = "create", resource = newJob }
          end
          return result
EOF