cat <<EOF | kubectl apply -n argocd -f -
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  resource.customizations.actions.batch_Job: |
    discovery.lua: |
      actions = {}
      if obj.metadata.labels and obj.metadata.labels["argocd.custom-action/retryable"] == "true" then
        actions["restart"] = {}
      end
      return actions
    definitions:
      - name: restart
        title: Restart Job
        message: Restarting Job...
        icon: replay
        action.lua: |
          local os = require("os")
          local result = {}

          local function deepCopy(obj)
            local lookup = {}
            local function _copy(o)
              if type(o) ~= "table" then return o end
              if lookup[o] then return lookup[o] end
              local new = {}
              lookup[o] = new
              for k, v in pairs(o) do new[_copy(k)] = _copy(v) end
              return new
            end
            return _copy(obj)
          end

          if obj then
            local baseName = obj.metadata.name or "job"
            if #baseName > 40 then baseName = baseName:sub(1, 40) end

            local newJob = {
              apiVersion = "batch/v1",
              kind = "Job",
              metadata = {},
              spec = deepCopy(obj.spec or {})
            }
            newJob.metadata.name = baseName .. "-rst-" .. os.time()
            newJob.metadata.namespace = obj.metadata.namespace
            
            -- Copy Labels
            newJob.metadata.labels = deepCopy(obj.metadata.labels or {})
            newJob.metadata.labels["argocd-action"] = "restarted-job"

            -- Clean Annotations
            if obj.metadata.annotations then
              newJob.metadata.annotations = deepCopy(obj.metadata.annotations)
              newJob.metadata.annotations["argocd.argoproj.io/hook"] = nil
              newJob.metadata.annotations["argocd.argoproj.io/tracking-id"] = nil
              newJob.metadata.annotations["kubectl.kubernetes.io/last-applied-configuration"] = nil
            end

            -- Clean Spec
            newJob.spec.selector = nil
            if newJob.spec.template then
               if not newJob.spec.template.metadata then newJob.spec.template.metadata = {} end
               newJob.spec.template.metadata.labels = deepCopy(newJob.metadata.labels)
               
               -- === FIX FOR "cannot unmarshal array" ERROR ===
               -- This removes empty 'resources' tables so they don't become '[]' in JSON
               if newJob.spec.template.spec then
                 local function cleanContainers(containers)
                   if containers then
                     for _, c in pairs(containers) do
                       -- If resources is empty table, set to nil to avoid JSON array serialization
                       if c.resources and next(c.resources) == nil then
                         c.resources = nil
                       end
                     end
                   end
                 end
                 cleanContainers(newJob.spec.template.spec.containers)
                 cleanContainers(newJob.spec.template.spec.initContainers)
               end
               -- ==============================================
            end

            result[1] = { operation = "create", resource = newJob }
          end
          return result
EOF